# -*- coding: utf-8 -*-
"""Assignment 06 VNP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8VP6VUudGb3SbzfYoZdiP0m5Mn6er06
"""

# Stress When depth is constant
Q = float (input ("Enter the value of Load in kN: "))
N= int (input ("Number of data values of radial distance: "))
pi = 3.14159265359
Z = float (input ("Depth: "))
r = []
for i in range (1, N+1):
  print ("Enter radial distance in m".format (i))
  Value_r = float(input () )
  r.append (Value_r)
  Stress = ((3*Q)/(2*pi*Z*Z))*(((1 / (1+((Value_r/Z)**2))))**2.5)
  print("Stress:" , Stress, "kN/m^2")